learning_log/urls.py
from django.contrib import admin
from django.urls    import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

app_name ='nameapp'

learning_logs/urls.py
'''
Определяет схемы URL для learning_logs.

'''


from django.urls import path, re_path

from .           import views


urlpatterns = [
    # Домашняя страница.
    path('', views.index, name='index'),

    # Вывод всех тем.
    path('topics/', views.topics, name='topics'),

    # Страница с подробной информацией по отдельной теме.
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # Страница для добавления новой темы.
    path('new_topic/', views.new_topic, name='new_topic'),

    # Страница для добавления новой записи.
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Страница для редактирования записи.
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    # Страница для удаления записи.
    re_path(r'^delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),
]

app_name ='nameapp'

users/urls.py
'''
Определяет схемы URL для пользователей.

'''

from django.urls               import path
from django.contrib.auth.views import LoginView 

from .                         import views


urlpatterns = [
    # Страница входа.
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Страница выхода.
    path('logout/', views.logout_view, name='logout'),

    # Страница регистрации.
    path('register/', views.register, name='register'),
]

app_name ='nameapp'

learning_logs/models.py
from django.db                  import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    '''
    Тема, которую изучает пользователь.

    '''
    
    text       = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner      = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        '''
        Возвращает строковое представление модели.

        '''

        return self.text


class Entry(models.Model):
    '''
    Информация, изученная пользователем по теме.

    '''

    STATUS_CHOICES = [
            ('pr', 'Private'),
            ('pb', 'Published'),
    ]

    VERIF_STATUS = [
        ('ok', 'Verified'),
        ('no', 'Reject'),
    ]

    topic        = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text         = models.TextField()
    date_added   = models.DateTimeField(auto_now_add=True)    
    entry_status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='')
    verified_adm = models.CharField(max_length=2, choices=VERIF_STATUS, default='')
    tag          = models.CharField(max_length=100, default='')


    class Meta:
        verbose_name_plural = 'entries'


    def __str__(self):
        '''
        Возвращает строковое представление модели.

        '''

        if len(self.text) >= 50:
            return self.text[:50] + '...'

        else:
            return self.text[:50]


'''class ForVerification(Entry):
    
    #Модель, наследуемая от Entry, чтобы отобразить 
     #записи на сайте администратора в отдельной графе.

    

    status       = Entry.objects.filter(entry_status='pb')'''

learning_logs/forms.py
from django  import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model  = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model   = Entry
        fields  = ['text', 'entry_status']
        labels  = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts               import render, get_object_or_404
from django.urls                    import reverse, reverse_lazy
from django.http                    import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.utils.decorators        import method_decorator
from django.db.models               import ProtectedError
from django.views.generic.edit      import DeleteView

from .models                        import Topic, Entry
from .forms                         import TopicForm, EntryForm


def index(request):
    '''
    Домашняя страница приложения Learning Log.
    
    '''

    entries = Entry.objects.filter(entry_status='pb', verified_adm='ok').order_by('-date_added')
    context = {'entries': entries}

    return render(request, 'learning_logs/index.html', context)

@login_required
def topics(request):
    '''
    Выводит список тем.

    '''

    topics  = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}

    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''
    Выодит одну тему и все ее записи.

    '''

    topic = Topic.objects.get(id=topic_id)

    # Проверка того, что тема принадлежит текущему пользователю.
    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''
    Определяет новую тему.

    '''

    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()

    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)

        if form.is_valid():
            new_topic       = form.save(commit=False)
            new_topic.owner = request.user

            new_topic.save()

            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}

    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''
    Добавляет новую запись по конкретной теме.
    
    '''

    topic = Topic.objects.get(id=topic_id)
    
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()

    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry       = form.save(commit=False) 
            new_entry.topic = topic
            entry_status    = form.cleaned_data.get("entry_status")

            new_entry.save()

            return HttpResponseRedirect(reverse('learning_logs:topic', 
                                            args=[topic_id]))

    context = {'topic': topic, 'form': form}

    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''
    Редактирует существующую запись.

    '''

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)

    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('learning_logs:topic', 
                                            args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}

    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    '''
    Удаляет существующую запись.

    '''

    
    obj   = Entry.objects.get(id=entry_id)
    topic = obj.topic

    check_topic_owner(request, topic)

    if request.method == "POST":
        obj.delete()

        return HttpResponseRedirect(reverse('learning_logs:topics'))

    return render(request, 'learning_logs/delete_entry.html')

def check_topic_owner(request, topic):
    '''
    Проверяет, что пользователь, связанный с темой, 
     является текущим пользователем.

    '''

    if topic.owner != request.user:
        raise Http404

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <title>Learning Log</title>
  </head>
  <body>
    <!-- Статистическая навигационная панель -->

  <nav class="navbar navbar-expand-lg fixed-top bg-light navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log</a>

      <!-- Кнопка навигации будет отображаться на маленьких экраах. -->
      <button class="navbar-toggler" type="button" 
        data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <!-- Ссылки -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics 
              <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <span class="navbar-text"> 
              <a> Hello, {{ user.username }}. </a>
            </span>
            <li class="nav-item active"></li>                           
              <a class="nav-link" href="{% url 'users:logout' %}">log out
                <span class="sr-only">(current)</span></a>

          {% else %}
            <li class="nav-item active"></li>
              <a class="nav-link" href="{% url 'users:register' %}">register 
                <span class="sr-only">(current)</span></a>
              <a class="nav-link" href="{% url 'users:login' %}">log in
                <span class="sr-only">(current)</span></a>

          {% endif %}
        </ul>
      </div> <!-- /.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="pb-3 mt-3 mb-2 border-bottom">
      {% block header %}{% endblock header %}    
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </div> <!-- /container -->
  
  </body>

</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <div class="main">
        <form method="POST">{% csrf_token %}
            <h5><p class="pt-5">Are you sure you want to delete {{ obj }}?</p></h5>
            <input type="submit" value="Yes" class="btn btn-success">
            <a href="{% url 'learning_logs:topics' %}" class="btn btn-secondary" 
                role="button">No</a>
        </form>
    </div>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
  <h3 class="pt-5">Edit entry:</h3>
{% endblock header %}

{% block content %}

  <h5><a href='{% url "learning_logs:topic" topic.id %}'>{{ topic }}</a></h5>
  
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" 
    class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button class="btn btn-primary btn-lg" type="submit">Save changes</button>
    {% endbuttons %} 
  </form>
  
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
  <div class="jumbotron bg-secondary text-white">
    <h1 class="display-4 pt-4">Track your learning.</h1> 
  </div>
{% endblock header %}

{% block content %}

  {% if user.is_authenticated %}
  <div class="font-weight-light">
    <h5><p class="font-weight-light">Hello, {{ user.username }}!</p></h5>
  
  {% else %}
    <div class="my-4">
      <h5><p><a href="{% url 'users:register' %}">Register in account</a> to make
      your own Learning Log, and list the topics you're learning about.</p></h5>
      <h5><p>You can also leave a public record for all users.</p></h5>
      <h5><p>Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.</p></h5> 
    </div>

  {% endif %}

  {% for entry in entries %}
    <div class="card">
      <div class="card-header">
        <h5>
          {{ entry.date_added|date:"Y-m-d, H:i"}}
        </h5>
        {% if user.is_authenticated %}
          <h5><p class="font-weight-light">Post author: {{ user.username }}</p></h5>

        {% endif %}
      </div>
      <div class="card-body">
        <h6><p class="card-text">{{ entry.text|linebreaks }}</p></h6>
      </div>
    </div>
    <p></p>

  {% endfor %}
  
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
  <h3 class="pt-5">Add a new entry:</h3>
{% endblock header %}

{% block content %}

  <h5><a href='{% url "learning_logs:topic" topic.id %} '">{{ topic }}</a></h5>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" 
    class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button class="btn btn-primary btn-lg" type="submit">Add entry</button>
    {% endbuttons %}  
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
  <h3 class="pt-5">Add a new topic:</h3>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'learning_logs:new_topic' %} " method='POST' 
    class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button class="btn btn-primary btn-lg" type="submit">Add topic</button>
    {% endbuttons %}

  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h3 class="pt-5"> {{ topic }} </h3>
{% endblock header %}

{% block content %}
<p>
  <h6><a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a></h6>
</p>

{% for entry in entries %}
  <div class="card">
    <div class="card-header">
      <h5>
        {{ entry.date_added|date:'M d, Y H:i' }}      
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a>              
          <a class="text-danger" href="{% url 'learning_logs:delete_entry' entry.id %}">
            delete entry</a>              
        </small>
      </h5>
    </div>
    <div class="card-body">
      <h6><p class="card-text">{{ entry.text|linebreaks }}</p></h6>
    </div>
  </div> <!-- card -->
  <p></p>

{% empty %}
  <h5>There are no entries for this topic yet.</h5>

{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h3 class="pt-5">Topics</h3>
{% endblock header %}

{% block content %}

<h5 class="mb-4"><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h5> 

  <ul>
    {% for topic in topics %}
      <li>
        <h5>
          <a class='pr-1' href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>          
        </h5>
    </li>

    {% empty %}
      <li>No topics have been added yet.</li>

    {% endfor %}
  </ul>

{% endblock content %}